const cardata = [
    {
      id: 1,
      title: 'BMW',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      carid: "0007",
      carbrand: "BMW",
      model: "BMWX5",
      seatingcapacity: "4",
      plateno: "0007",
      fueltype: "p-unleaded",
      capacity: "NA",
      year: "1916",
      color: "Black",
      hcharge: "NA",
      dcharge: "NA",
      wcharge: "NA",
      action: "NA",
      

    
    },
    {
      id: 2,
      title: 'BMW',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      carid: "0007",
      carbrand: "BMW",
      model: "BMWX5",
      seatingcapacity: "4",
      plateno: "0008",
      fueltype: "p-unleaded",
      capacity: "NA",
      year: "1916",
      color: "Black",
      hcharge: "NA",
      dcharge: "NA",
      wcharge: "NA",
      action: "NA",
      

    
    },
    {
      id: 3,
      title: 'BMW',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      carid: "0009",
      carbrand: "BMW",
      model: "BMWX5",
      seatingcapacity: "4",
      plateno: "0007",
      fueltype: "p-unleaded",
      capacity: "NA",
      year: "1916",
      color: "Black",
      hcharge: "NA",
      dcharge: "NA",
      wcharge: "NA",
      action: "NA",
      

    
    },
    {
      id: 4,
      title: 'BMW',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      carid: "0010",
      carbrand: "BMW",
      model: "BMWX5",
      seatingcapacity: "4",
      plateno: "0007",
      fueltype: "p-unleaded",
      capacity: "NA",
      year: "1916",
      color: "Black",
      hcharge: "NA",
      dcharge: "NA",
      wcharge: "NA",
      action: "NA",
      

    
    },
    {
      id: 5,
      title: 'BMW',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      carid: "0011",
      carbrand: "BMW",
      model: "BMWX5",
      seatingcapacity: "4",
      plateno: "0007",
      fueltype: "p-unleaded",
      capacity: "NA",
      year: "1916",
      color: "Black",
      hcharge: "NA",
      dcharge: "NA",
      wcharge: "NA",
      action: "NA",
      

    
    },
    {
      id: 6,
      title: 'BMW',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      carid: "0012",
      carbrand: "BMW",
      model: "BMWX5",
      seatingcapacity: "4",
      plateno: "0007",
      fueltype: "p-unleaded",
      capacity: "NA",
      year: "1916",
      color: "Black",
      hcharge: "NA",
      dcharge: "NA",
      wcharge: "NA",
      action: "NA",
      

    
    },
    
  ];
  
  export default cardata;
  