const cardata = [
    {
      id: 1,
      title: 'Rohit',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      sales: 1647,
      stock: 62,
      bookingfrom: "surat",
      bookingto: "pune",
      carname: "BMW",
      type: "luxuryvehicle",
      bookingstatus: "NA",
      remark: "ok",
      charges: "NA",
      action: "NA",

    
    },
    {
      id: 2,
      title: 'Rohit bharti',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      sales: 1647,
      stock: 62,
      bookingfrom: "surat",
      bookingto: "pune",
      carname: "BMW",
      type: "luxuryvehicle",
      bookingstatus: "NA",
      remark: "ok",
      charges: "NA",
      action: "NA",

    
    },
    {
      id: 3,
      title: 'Kumar',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      sales: 1647,
      stock: 62,
      bookingfrom: "surat",
      bookingto: "pune",
      carname: "BMW",
      type: "luxuryvehicle",
      bookingstatus: "NA",
      remark: "ok",
      charges: "NA",
      action: "NA",

    
    },
    
    {
      id: 4,
      title: 'Dishank',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      sales: 1647,
      stock: 62,
      bookingfrom: "surat",
      bookingto: "pune",
      carname: "BMW",
      type: "luxuryvehicle",
      bookingstatus: "NA",
      remark: "ok",
      charges: "NA",
      action: "NA",

    
    },
    {
      id: 5,
      title: 'bill',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      sales: 1647,
      stock: 62,
      bookingfrom: "surat",
      bookingto: "pune",
      carname: "BMW",
      type: "luxuryvehicle",
      bookingstatus: "NA",
      remark: "ok",
      charges: "NA",
      action: "NA",

    
    },
    {
      id: 6,
      title: 'Raghav',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      sales: 1647,
      stock: 62,
      bookingfrom: "surat",
      bookingto: "pune",
      carname: "BMW",
      type: "luxuryvehicle",
      bookingstatus: "NA",
      remark: "ok",
      charges: "NA",
      action: "NA",

    
    },
    {
      id: 7,
      title: 'Raghav',
      img: '/assets/img/products/marble-cake-thumb.jpg',
      category: 'Car',
      createDate: '02.04.2018',
      status: 'ON HOLD',
      statusColor: 'primary',
      description: 'Wedding cake with flowers Macarons and blueberries',
      sales: 1647,
      stock: 62,
      bookingfrom: "surat",
      bookingto: "pune",
      carname: "BMW",
      type: "luxuryvehicle",
      bookingstatus: "NA",
      remark: "ok",
      charges: "NA",
      action: "NA",

    
    },
    
  ];
  
  export default cardata;
  